version: '3'

services:
  rabbit:
    container_name: booking-rabbit
    image: rabbitmq:3.7-management
    ports:
      - "15673:15672" # Exposing RabbitMQ web management on different port for convenience
    restart: always
    volumes:
      - rabbit_data:/var/lib/rabbitmq  # Persist RabbitMQ data

  mysql:
    container_name: booking-mysql
    image: mysql:5.7
    ports:
      - "3307:3306" # Exposing MySQL on different port for convenience
    environment:
      MYSQL_DATABASE: "microservices_soa_h"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always

  booking:
    build: ./booking
    container_name: booking-services
    depends_on:
      - rabbit
      - mysql
    ports:
      - "8001:8000"
    links:
      - "rabbit:rabbit"
      - "mysql:mysql"
    environment:
      MYSQL_PASSWORD: "password"
      MYSQL_HOST: "mysql"
      MYSQL_DB: "microservices_soa_h"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_MANAGEMENT_PORT: "15672"

  review:
    build: ./review
    container_name: review-services
    depends_on:
      - rabbit
      - mysql
    ports:
      - "8002:8000"
    links:
      - "rabbit:rabbit"
      - "mysql:mysql"
    environment:
      MYSQL_PASSWORD: "password"
      MYSQL_HOST: "mysql"
      MYSQL_DB: "microservices_soa_h"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_MANAGEMENT_PORT: "15672"

  gateway:
    build: ./gateway
    container_name: gateway-services
    depends_on:
      - rabbit
    ports:
      - "8004:8000"
    links:
      - "rabbit:rabbit"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_MANAGEMENT_PORT: "15672"

volumes:
  mysql_data:
    driver: local
  rabbit_data:
    driver: local